kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ztap
networking:
  disableDefaultCNI: true
  podSubnet: 10.244.0.0/16
nodes:
  - role: control-plane
  - role: worker
    labels:
      ztap.io/node-pool: monitoring
  - role: worker
    labels:
      ztap.io/node-pool: inference
  - role: worker
    labels:
      ztap.io/node-pool: tenant-a
  - role: worker
    labels:
      ztap.io/node-pool: tenant-b
